### ISSUE TITLE
Unexpected state values returned from service.signInCustomer

### ISSUE THREAD

**Issue by ArchangelGabriel** [bigcommerce/checkout-sdk-js#422] opened 2018-10-01 03:23 UTC
Running this piece of code:
```javascript
import {createCheckoutService} from '@bigcommerce/checkout-sdk'
const service = createCheckoutService()
service.loadCheckout().then(() => {
  service.signInCustomer({
    email: 'test@test.com',
    password: 'test',
  }).then((state) => console.log(state.data.getCustomer()))
})
```

Logs:
```javascript
{
  "id": 0,
  "isGuest": true,
  "email": "",
  "firstName": "",
  "lastName": "",
  "fullName": "",
  "addresses": [],
  "storeCredit": 0
}
```

Am I missing something here?

**Comment by ArchangelGabriel** [comment] 2018-10-01 16:53
*Additional Info*

Immediately after invoking service.signInCustomer(), I am getting 2 http requests in my network tab:
1. http://localhost:3000/internalapi/v1/checkout/customer
2. http://localhost:3000/api/storefront/checkout/7b8791c4-33aa-445e-8a8f-92b6d0d172e7?include=cart.lineItems.physicalItems.options%2Ccart.lineItems.digitalItems.options%2Ccustomer%2Cpayments%2Cpromotions.banners

Request number 1 contains the correct customer data
Request number 2 contains an empty customer data

I believe the response data from request number 2 overrides the value received from request number 1.

**Comment by capsula4** [comment] 2018-10-12 03:59
It's expected to have 2 HTTP requests. The first one is the sign in request (PUT/POST), and the second one hydrates the customer state using our Storefront API. It looks like there could be a bug in the API, but the JS behaviour seems correct.

Can you consistently reproduce this issue? Maybe attach a HAR file when you attempt to sign in the user?

**Comment by ArchangelGabriel** [comment] 2018-10-16 15:04
Attached is the HAR file:

[localhost.har](https://pastebin.com/AehxpFsA)

In summary here's what happened as per network request:

```text
1. sign in
2. sign in failed
3. sign in
4. sign in success
5. sign out
6. sign out success
7. sign in
8. sign in failed
9. sign in
10. sign in success
```

I typically have to submit the form twice for the login to succeed.

**Comment by ONeill45** [comment] 2018-11-30 15:06
Any updates to this? I am having the same issue with signing in. I typically have to sign in multiple times to get the state to update. Same with sign out

**Comment by AllenDiao** [comment] 2019-03-03 14:51
same issue here (multiple times signin signout). Any fix yet?

**Comment by icatalina** [comment] 2019-03-05 11:39
Hi @ArchangelGabriel! Are you using stencil-cli? 

What about you @ONeill45 and @AllenDiao?

**Comment by AllenDiao** [comment] 2019-03-16 12:32
@icatalina Yes, I am using Stencil-cli runing on localhost.

When signout, the request go through with correct response.
Request URL: http://localhost:3003/internalapi/v1/checkout/customer
Request method: DELETE

data | {…}
customer | {…}
isGuest | true
...

But the next request to checkout API returns incorrect response
Request URL: http://localhost:3003/api/storefront/checkout/.....
Request method: GET

customer | {…}
id | 1
isGuest | false

Refreshing page, customer info is correct

**Comment by icatalina** [comment] 2019-03-18 10:22
Ok, it shouldn't be an issue in production, but I understand the frustration. I'll take note and we'll investigate a bit further.

**Comment by adaamcollins** [comment] 2019-03-22 11:28
@icatalina I can confirm this **isn't** an issue in production, it's a local Stencil CLI only issue - we first saw this a number of weeks ago. So it's not a major issue, but is a little frustrating at first.

Also - to note - this doesn't happen every time you run the `signInCustomer` function. It happens about 50% of the time.

It seems to be something to do with the order of the network requests, if they are in the right order, then it works, otherwise if they're in the opposite order, it doesn't work.

**Comment by icatalina** [comment] 2019-03-28 21:35
Hey @adaamcollins,

Thanks for confirming this. Can you pin point it to some specific network requests? the sdk uses observables to make sure the request that should follow certain order, do... to avoid race conditions. We might have missed one...

**Comment by adaamcollins** [comment] 2019-03-29 10:34
These are the two requests in question:

1. POST customer details

<img width="613" alt="Screenshot 2019-03-29 at 10 16 39" src="https://user-images.githubusercontent.com/25459663/55226009-de58f300-520b-11e9-9cd4-d0c92342cac4.png">

2. Get updated checkout state

<img width="615" alt="Screenshot 2019-03-29 at 10 16 50" src="https://user-images.githubusercontent.com/25459663/55226010-def18980-520b-11e9-9af8-ca3ba38219e1.png">

Both of the above requests are a result of the `signInCustomer` method.

As you can see, request 1 has 'date/time' which is later than request 2, so the SDK is getting the updated checkout state before the post request has completed.

As mentioned, this does not happen all of the time on local and it **never** happens in production. 

On local, sometimes request 2 takes place correctly after request 1 and logging the customer in works fine in those instances.

**Note** that this affects signing customers in and out only. No other requests have this issue.

Also, FYI - here's the two responses for each request.

Request 1 response contains customer object as expected -

<img width="628" alt="Screenshot 2019-03-29 at 10 23 04" src="https://user-images.githubusercontent.com/25459663/55226395-d3eb2900-520c-11e9-96e2-5cdcdb767de3.png">

Request 2 response contains a blank customer object -

<img width="624" alt="Screenshot 2019-03-29 at 10 24 14" src="https://user-images.githubusercontent.com/25459663/55226588-3c3a0a80-520d-11e9-84fe-cd99255dd8e5.png">

**Comment by icatalina** [comment] 2019-04-04 22:15
Thanks for the detailed information. By checking the SDK it looks like the 2 request should happen in series, I'm not sure what's going on. We'll try to replicate it and see if we can spot the issue.

**Comment by fthobe** [comment] 2019-07-05 19:34
Hi @icatalina , has this ever been resolved and can be referenced in a bugfix?

**Comment by fresh5447** [comment] 2019-07-10 23:34
Welp lost about 10 hours trying to get this to work before stumbling upon this issue. That's been open since September.... wow

**Comment by icatalina** [comment] 2019-07-12 02:55
Not yet, sorry @fthobe.

**Comment by LordZardeck** [comment] 2019-07-25 13:18
I am having the same issue. Was worried I was doing something wrong, but I can confirm with a clean install of the SDK this issue occurs. It happens more often than 50% though for me. @icatalina so this is an issue with bigcommerce/stencil-cli and not the checkout sdk?

**Comment by hatertron3000** [comment] 2019-10-30 22:00
The same issue exists for the service.signCustomerOut method. I thought I was going insane until I found this. Thanks for looking into it!

**Comment by davidchin** [comment] 2019-12-18 12:30
Sorry everyone, I just had a chance to look at this issue. It seems `stencil-cli` caches all HTTP responses and [uses the cache](https://github.com/bigcommerce/stencil-cli/blob/master/server/plugins/renderer/renderer.module.js#L116) if the same GET request is made in the last 15 seconds. The logic doesn't look right to me as it doesn't seem to honour the cache-control header of the responses. Anyway, before we can put in a fix in, I think the current workaround for this issue to run CLI with the [caching option](https://github.com/bigcommerce/stencil-cli/blob/ed73b24757484ca6261319515c5f427b62bb5d80/bin/stencil-start#L41https://github.com/bigcommerce/stencil-cli/blob/ed73b24757484ca6261319515c5f427b62bb5d80/bin/stencil-start#L41) turned off. i.e.: `stencil start --no-cache`. Please let me know if this helps. Thanks!

cc @ankurbigcomm

**Comment by adaamcollins** [comment] 2019-12-18 13:44
@davidchin I just had some time to check this out and you are right, it does appear to be the cache. When running `stencil start --no-cache`, I don't experience the issue at all.

**Comment by davidchin** [comment] 2019-12-20 03:20
I think the latest version of `stencil-cli` (`v1.21.4`) should fix the issue. You shouldn't need to use `--no-cache` workaround anymore. So I'm going to close this issue 👍

**Closed by davidchin** 2019-12-20 03:20 UTC
Labels: investigate
