### ISSUE TITLE
Draft Order not working 

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/checkout-sdk-js#534] opened 2019-03-06 18:47 UTC
For some reason unknown to us draft orders don't wont work in custom checkout: 

- the custom product is correctly added to the cart 
- when going to the checkout, the checkout appears empty

Seen on Chrome (latest), OSX (latest), Macbook Pro 15" Retina
Video: [Youtube](https://youtu.be/Ic__oe3tmZQ)
Test Link: [Draft Order](https://www.ricomprostaging.it/cart.php?action=loadSavedQuote&quoteToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvd3d3LnJpY29tcHJvc3RhZ2luZy5pdCIsImlhdCI6MTU1MTg5NzY2MSwiZXhwIjoxNTU0NDAzMjYxLCJkb21haW4iOnsiY2FydCI6eyJpZCI6IjM4YTZkYjViLTVlNDUtNDAyYS1iYzAzLWEzOGYwOTBjODY3YSJ9fX0.m064lwKgWBvzoYOrw1KyJCuN9e9UHW307CBlBh-eWSY)

`Uncaught (in promise) TypeError: Cannot read property 'imageUrl' of undefined
    at n (theme-bundle.chunk.22.js:1)
    at theme-bundle.chunk.22.js:1
    at x (theme-bundle.main.js:70)
    at Generator._invoke (theme-bundle.main.js:70)
    at Generator.t.(anonymous function) [as next] (https://cdn11.bigcommerce.com/s-pqeliom1as/stencil/af777a10-2226-0137-c6c4-0242ac11001f/e/5ac69dc0-1ca0-0137-61a6-0242ac110025/dist/theme-bundle.main.js:70:17264)
    at i (theme-bundle.chunk.22.js:1)
    at theme-bundle.chunk.22.js:1
n @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
x @ theme-bundle.main.js:70
(anonymous) @ theme-bundle.main.js:70
t.(anonymous function) @ theme-bundle.main.js:70
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
Promise.then (async)
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
Promise.then (async)
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
x @ theme-bundle.main.js:70
(anonymous) @ theme-bundle.main.js:70
t.(anonymous function) @ theme-bundle.main.js:70
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
Promise.then (async)
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
Promise.then (async)
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
Promise.then (async)
i @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.chunk.22.js:1
(anonymous) @ theme-bundle.main.js:41
l @ theme-bundle.main.js:39
u @ theme-bundle.main.js:39
setTimeout (async)
(anonymous) @ theme-bundle.main.js:39
c @ theme-bundle.main.js:39
add @ theme-bundle.main.js:39
(anonymous) @ theme-bundle.main.js:39
t.Deferred @ theme-bundle.main.js:70
then @ theme-bundle.main.js:39
C.fn.ready @ theme-bundle.main.js:39
t.load @ theme-bundle.main.js:41
(anonymous) @ theme-bundle.main.js:60
x @ theme-bundle.main.js:70
(anonymous) @ theme-bundle.main.js:70
t.(anonymous function) @ theme-bundle.main.js:70
i @ theme-bundle.main.js:60
(anonymous) @ theme-bundle.main.js:60
(anonymous) @ theme-bundle.main.js:39
t.exports @ theme-bundle.main.js:41
g.(anonymous function) @ theme-bundle.main.js:41
y @ theme-bundle.main.js:41
b @ theme-bundle.main.js:41`

**Comment by davidchin** [comment] 2019-03-17 23:45
Hi @fthobe, thanks for submitting this issue. It's a bit hard to tell from the minified code and without the help of a source map, but I believe somewhere in your code you're trying to access `lineItems.physicalItems[0].imageUrl` directly, i.e.:

<img width="539" alt="Screen Shot 2019-03-18 at 10 28 24 am" src="https://user-images.githubusercontent.com/667603/54499711-eb9ef380-4968-11e9-98ba-920e3712c217.png">

The example you provided throws an error because `physicalItems` is an empty array - it doesn't contain an item therefore you won't be able to access `imageUrl` property. So I suggest you do a null check before accessing the property.

Anyway, it seems this issue is not related to the SDK library itself, but rather the application using the library. So I'm going to close this issue. But feel free to reopen it if you think the problem is with library. :)

**Closed by davidchin** 2019-03-17 23:45 UTC
