### ISSUE TITLE
Cannot save address in BC using shouldSaveAddress flag

### ISSUE THREAD

**Issue by catokx** [bigcommerce/checkout-sdk-js#1041] opened 2020-12-11 11:53 UTC
Good morning, i'm using bigcommerce checkout sdk version 1.116.0.
I'm trying to use the shouldSaveAddress = true flag in address json.

When i place the order i cannot find the shipping or billing address into the bigcommerce customer account.

**Comment by capsula4** [comment] 2020-12-14 02:51
Just double-checking, are you using `shouldSaveAddress` with a logged-in customer? Was the order successfully placed?

**Comment by fthobe** [comment] 2020-12-14 07:52
Hey @capsula4 , order is finalized successfully and customer is logged in. We don't allow guest checkout on our page. We also tried to send your exact test address and it didn't work. The entire rest of the address is correctly added to the order.

**Comment by capsula4** [comment] 2020-12-14 21:48
I haven't been able to reproduce the issue. Is there any chance you could confirm that `shouldSaveAddress: true` is present right before the order is being placed? Maybe there's some other action before the order is placed that updates that attribute?

**Comment by bc-0dp** [comment] 2024-02-15 16:53
@catokx are we good to close this?

**Comment by bc-0dp** [comment] 2024-02-27 09:51
Closing this due to inactivity

**Closed by bc-0dp** 2024-02-27 09:51 UTC
