### ISSUE TITLE
SDK returning error when submitting order through applepay and googlepay

### ISSUE THREAD

**Issue by ArishAzizSG** [bigcommerce/checkout-sdk-js#2012] opened 2023-06-09 06:02 UTC
**Describe the bug**
We have developed a Custom checkout experience using the Checkout SDK. Recently, new options and features were introduced in the checkout. We have been using the SDK without any issues related to Apple Pay and Google Pay till now. Orders were being created and the checkout flow was completed successfully. However, after the recent changes were made to the checkout, we started encountering problems when submitting orders through Apple Pay and Google Pay. The error we are receiving from the SDK is "Attempt to assign a readonly property" when the service.submitOrder method is called, here the reference of the method in SDK [link](https://github.com/bigcommerce/checkout-sdk-js/blob/68a07a980d7aab4b8196acbdf9b13744781b25ee/src/checkout/checkout-service.ts#L250). We believe that the recent changes to the checkout are causing a conflict with the SDK.

The service.submitOrder method is working fine when submitting orders through Credit Card, but Apple Pay and Google Pay are experiencing issues. We have also contacted Bigcommerce support regarding the issue, and they shared the following logged error on their side:

"BigPay::ConfigurationError::ProfileNotFound: No configs found for store: XXXXXXXXXX, gateway_name: applepay"
Note: XXXXXXXXXX was the store info, which was redacted!

**To Reproduce**
The steps to reproduce the issue may vary depending on the custom checkout experience.

**Expected behavior**
The Apple Pay payment panel should appear, and when selecting an account in the Google Pay window, the order should be created. However, currently nothing happens when attempting these actions.

**Screenshots**
Screenshot of the error logged in the console when Apple Pay is selected:
https://i.imgur.com/fhmlXly.jpg

**Additional context**
We have double-checked the configuration for Apple Pay and Google Pay on Bigcommerce. We have also tried switching between the new options introduced in the checkout, as referenced [here](https://support.bigcommerce.com/s/article/Optimized-Single-Page-Checkout?language=en_US#custom). Additionally, we have confirmed with Checkout.com that Apple Pay and Google Pay are properly configured for our account. We have attempted to resolve the issue by disabling and re-enabling the Apple Pay and Google Pay options on Bigcommerce.

The SDK is causing issues with the payment methods that could potentially impact sales. We urgently require assistance with this matter and need a resolution as soon as possible. Please let us know if you need any additional information from our side to help resolve this issue.

**Comment by animesh1987** [comment] 2023-06-09 06:31
Hey @ArishAzizSG don't think we have made changes on payment integrations side for some time. 

Out of curiosity do the buttons work fine on cart page? Is there a link to the store that you can attach for us to look at? 

Also are you using the latest SDK version?

**Comment by ArishAzizSG** [comment] 2023-06-09 06:57
Hello, @animesh1987! I appreciate your prompt response. I wanted to let you know that the buttons on the cart page are indeed functional. For the testing, here is the staging environment for you to access: https://karenwazen-sandbox.mybigcommerce.com/all/

Regarding the SDK version, we have carefully followed the provided documentation. As a result, we are using the following link for the SDK: 

https://checkout-sdk.bigcommerce.com/v1/loader.js

**Comment by animesh1987** [comment] 2023-06-09 07:18
Thanks for the link, I can see apple pay button rendered fine on cart page. But don't see don't see it on checkout page. 

Checkout page seems to be quite custom as you have stated already. Also the toggles listed above related to buttons on top of page should not have any effect on custom checkout. Can also see SDK version is latest as well. But don't see apple pay wallet button on checkout page.

**Comment by ArishAzizSG** [comment] 2023-06-09 07:23
Could you please confirm with the device you are using ? and also the country which is selected in billing section of the checkout ? If its a apple device and country is selected where Applepay is support, could please try refreshing the page ?

Yes we know, but the steps were recommended by bigcommerce support to toggle the option which will add buttons on the top page, to see if things could work but it didn't.

**Comment by animesh1987** [comment] 2023-06-09 07:28
I am using safari and fairly certain the apple pay is supported in my region as I have used it for other stores. Thanks for letting us know about support as they are changes for native OOPC mainly?

Have you tried to switch your store to native checkout and test the flow?

**Comment by ArishAzizSG** [comment] 2023-06-09 07:44
The support didn't mentioned any specifics if the options were for native or for custom checkout.

Is it possible for you to share the reference or any specifics for the image ? and it seems the apple pay is now visible.

Yes, we previously tried switching between custom and native and we also confirm this just now, the native flow is indeed working.

**Comment by ArishAzizSG** [comment] 2023-06-12 10:36
Sure @animesh1987 ,

Here is the test flow (assuming you are using desktop safari):
1: Open the link for the sandbox environment (https://karenwazen-sandbox.mybigcommerce.com/all/)
2: Add a product to cart
3: Continue to Checkout
4: Once the checkout is loaded, press (control + command + r) to switch into responsive mode and select iPhone 8 Plus from the safari responsive panel
5: Open the developer console with (option + command + i)
6: once you have filled the shipping details (assuming the my billing address will be same as shipping option is checked)
7: Select the Other payment methods in the (2 Payment) section of the checkout
8: Select the Apple Pay payment method
9: Clear the console, as till now there will a lot of console.logs
10: Click the Place order and observe the developer console for logs. (You will receive the error: Attempt to assign a readonly property from the SDK)

We also would like to share that the total number of orders which we receive after deploying custom checkout are 103 orders.

**Comment by animesh1987** [comment] 2023-08-09 05:39
Hey @ArishAzizSG this dropped out of the radar, from the instructions above seems like we are referring to payment methods in payment step. Is this still an issue?

**Comment by ArishAzizSG** [comment] 2023-08-09 05:50
Hey @animesh1987 

The issue shared above got resolved, the payments are now processing, but while looking through SDK documentation i didn't find where the error handling message is shared when the payment gets expired or declined due to insufficient funds, 3ds fail or any other reason.

**Comment by animesh1987** [comment] 2023-08-09 06:01
That's good to hear that the issue got resolved. As the the error handling messages, with apple pay it can be tricky as we get codes from them which are quite cryptic. But we can look at our error messaging going forward and how we can improve that.

Since the issue is resolved I am going to close this issue.

**Closed by animesh1987** 2023-08-09 06:01 UTC

**Comment by ArishAzizSG** [comment] 2023-08-09 06:04
Apart from CheckoutCom Applepay, are the same cryptic codes are shared when errors are received from CheckoutCom Google pay or CheckoutCom Credit Card if payment get failed, declined or expired ?

**Comment by animesh1987** [comment] 2023-08-09 13:22
Yes that will be correct, since we try and pass on messages from providers if mapped in our systems. We can have a look at improving them when we review the integrations.
