### ISSUE TITLE
Integrate ts file in cornerstone theme

### ISSUE THREAD

**Issue by thanicricket** [bigcommerce/checkout-sdk-js#745] opened 2019-11-14 13:02 UTC
Hi!

Any one help to integrate react ts file in cornerstone theme
```

_Originally posted by @icatalina in https://github.com/bigcommerce/checkout-sdk-js/issues/744#issuecomment-553621504_

**Comment by capsula4** [comment] 2019-11-14 23:03
duplicate of https://github.com/bigcommerce/checkout-sdk-js/issues/744

**Closed by capsula4** 2019-11-14 23:03 UTC
