### ISSUE TITLE
Is executeSpamCheck meant to be called just before the order is placed?

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/checkout-sdk-js#856] opened 2020-04-30 18:18 UTC
Is `executeSpamCheck` meant to be called just before `submitOrder`, or is it supposed to be called at some point earlier in the process?

I ask because the "protected by recaptcha" badge does not appear until `executeSpamCheck` is called. That means the badge is not there until the customer clicks to submit their order. I think typically the badge is visible throughout the checkout process, which would mean this method should actually be called in the very beginning or maybe when the payment step loads.

But then don't we risk validation expiring as they work their way through the checkout?

**Comment by flyingL123** [comment] 2020-04-30 18:22
Also, if an error occurs, why isn't that error appearing in `state.errors.getError()`. I see a request error occurring, but it's not showing up anywhere in the error collection.

**Comment by flyingL123** [comment] 2020-05-09 00:19
Hi @capsula4 - another issue related to this is that when the method is called from `localhost`, I receive a 429 Too Many Requests error every time. I've added my recaptcha keys in the BigCommerce control panel, and it seems to be working correctly on the live domain. I've also added localhost as an approved domain in the recaptch developer center. The widget renders correctly on localhost, but the BigCommerce `spam-protection` endpoint is returning the 429 Error. Do you know why this is happening? It's very hard to properly develop and test a checkout that uses the recaptcha if they behave differently on the real site vs local.

**Comment by dougep** [comment] 2020-11-26 05:00
Duplicate of https://github.com/bigcommerce/checkout-sdk-js/issues/933

**Closed by dougep** 2020-11-26 05:00 UTC
